/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
    },
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
    colors:{
      messageBg:"#020617",
      messageBodyBg:"#f3f4f6",
      inputbg:"#e5e7eb",
      favTxt:"#020617",
      personBg:"#e9e9f3",
      personMesTxt:"#7d7d81",
      dotBg:"#06d6a0",
      messageCountBg:"#bbf7d0",
      messageCountTxt:"#ed7b9a",
      plusBtn:"#0dd6a6",
      plusTxt:"#fff",
      newMessage:"#030712",
      modalOutBg:"#000000",
      modalHeadBg:"#06d6a0",
      modalCloseIcon:"#c9d2d4",
      modalBg:"#fafafa",
      modalInputBorder:"#808384",
      modalSearchBg:"#e64469",
      modalSearchHoverBg:"#cc3c5c",
      modalCloseTxt:"#999fd6",
      modalSendBtn:"#09d1a7",
      modalSendTxt:"#fff",
      modalContactTxt:"#5e6266",
      modalNameTxt:"#212529",
      channleModalBtnBg:"#f6f6f9",
      channelModalBtnHoverBg:"#d1d1d4",
      channelModalBtnTxt:"#64666a",
      channelModalCloseTxt:"#f16c8c",
      channleModalContactBg:"#f8f8f9",
      channelModalContactBodyBg:"#fff",
      channelModalCheckBoxBg:"#6d75c5",
      chatIconBg:"#7b7e82",
      sendInputBg:"#f6f6f9",
      typeingDotBg:"#06d6a0",
      inputMoreIconBg:"#cbd5e1",
      inputMoreBg:"#e5e7eb",
      inputMoreIcon:"#94a3b8",
      threeDotMenu:"#fff",
      threeDotMenuTxt:"#595d61",
      threeDotMenuHover:"#f8f9fa",
      phoneModalCameraBg:"#fcdae2",
      phoneModalCameraTxt:"#f05479",
      phoneModalVolBg:"#cdf7ec",
      phoneModalVolTxt:"#2cdcaf",
      phoneModalUserBg:"#dcedfc",
      phoneModalUserTxt:"#5babf2",
      phoneModalhangbg:"#f05479",
      phoneModalhangHoverbg:"#cb3c5e",
      phoneModalhangTxt:"#fff",
      phoneModalMsBg:"#44e0b8",
      phoneModalMsHoverBg:"#000",
      infoModalBg:"#e5e7eb",
      textInfo:"#020617",
      backBtnBg:"#06d6a0",
      backBtnTxt:"#fff",
      fileUploudBg:"#e9f0ff",
      fileUploudDlt:"#ef4444",
      modalChangeBg:"#10b981",
      pdfBg:"#ef4444",
      docxBg:"#2563eb",
      muted:"#7d7d81",
      checktxt:"#9ca3af"


    },
  },
  plugins: [],
}
